from sqlalchemy import create_engine, text

from config import DATABASE_URL, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME


DEFAULT_REST_SEC_AFTER = 120
DEFAULT_RPE = 6


def get_engine():
    if DATABASE_URL:
        return create_engine(DATABASE_URL)

    return create_engine(
        f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    )


def test_connection():
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(text("SELECT current_database();"))
        db_name = result.scalar()

    return db_name


def create_users_table():
    engine = get_engine()

    with engine.connect() as conn:
        conn.execute(
            text("""
                CREATE TABLE IF NOT EXISTS users (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    telegram_user_id bigint UNIQUE NOT NULL,
                    username text,
                    first_name text,
                    created_at timestamp NOT NULL DEFAULT now(),
                    updated_at timestamp NOT NULL DEFAULT now()
                )
            """)
        )
        conn.commit()


def get_or_create_user(
    telegram_user_id: int,
    username: str | None = None,
    first_name: str | None = None,
) -> int:
    create_users_table()
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                INSERT INTO users
                (
                    telegram_user_id,
                    username,
                    first_name,
                    created_at,
                    updated_at
                )
                VALUES
                (
                    :telegram_user_id,
                    :username,
                    :first_name,
                    now(),
                    now()
                )
                ON CONFLICT (telegram_user_id)
                DO UPDATE SET
                    username = EXCLUDED.username,
                    first_name = EXCLUDED.first_name,
                    updated_at = now()
                RETURNING id
            """),
            {
                "telegram_user_id": telegram_user_id,
                "username": username,
                "first_name": first_name,
            }
        )
        user_id = result.scalar_one()
        conn.commit()

    return user_id


def normalize_workout_row_defaults(row: dict) -> dict:
    normalized_row = dict(row)

    rest_sec_after = normalized_row.get("rest_sec_after")
    rpe = normalized_row.get("rpe")

    if rest_sec_after is None or rest_sec_after <= 0:
        normalized_row["rest_sec_after"] = DEFAULT_REST_SEC_AFTER

    if rpe is None or rpe <= 0:
        normalized_row["rpe"] = DEFAULT_RPE

    return normalized_row


def normalize_workout_rows_defaults(rows: list[dict]) -> list[dict]:
    return [normalize_workout_row_defaults(row) for row in rows]


def insert_workout_rows(rows: list[dict]):
    engine = get_engine()
    rows = normalize_workout_rows_defaults(rows)

    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO workouts 
                (
                    user_id,
                    date,
                    exercise,
                    category,
                    reps,
                    weight_kg,
                    rest_sec_after,
                    duration_sec,
                    rpe,
                    notes
                )
                VALUES 
                (
                    :user_id,
                    :date,
                    :exercise,
                    :category,
                    :reps,
                    :weight_kg,
                    :rest_sec_after,
                    :duration_sec,
                    :rpe,
                    :notes
                )
            """),
            rows
        )
        conn.commit()

#analytics_layer
#1. last rows
def get_last_workouts(limit: int = 10, user_id: int | None = None):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    id,
                    date,
                    exercise,
                    category,
                    reps,
                    weight_kg,
                    rest_sec_after,
                    duration_sec,
                    rpe,
                    notes
                FROM workouts
                WHERE (:user_id IS NULL OR user_id = :user_id)
                ORDER BY id DESC
                LIMIT :limit
            """),
            {
                "limit": limit,
                "user_id": user_id,
            }
        )

        rows = result.mappings().all()

    return rows


def get_latest_training_dates(limit: int = 10, user_id: int = 1):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    date,
                    COUNT(*) AS rows_count,
                    COUNT(DISTINCT exercise) AS exercises_count,
                    COALESCE(SUM(reps * weight_kg), 0) AS total_volume
                FROM workouts
                WHERE user_id = :user_id
                GROUP BY date
                ORDER BY date DESC
                LIMIT :limit
            """),
            {
                "user_id": user_id,
                "limit": limit,
            }
        )

        rows = result.mappings().all()

    return rows


def get_basic_stats():
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    COUNT(*) AS total_sets,
                    COUNT(DISTINCT date) AS training_days,
                    COUNT(DISTINCT exercise) AS unique_exercises,
                    COALESCE(SUM(reps), 0) AS total_reps,
                    COALESCE(SUM(reps * weight_kg), 0) AS total_volume,
                    MIN(date) AS first_date,
                    MAX(date) AS last_date
                FROM workouts
            """)
        )

        row = result.mappings().one()

    return row


def get_basic_stats_for_period(
    user_id: int = 1,
    start_date=None,
    end_date=None,
):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    COUNT(*) AS total_sets,
                    COUNT(DISTINCT date) AS training_days,
                    COUNT(DISTINCT exercise) AS unique_exercises,
                    COALESCE(SUM(reps), 0) AS total_reps,
                    COALESCE(SUM(reps * weight_kg), 0) AS total_volume,
                    MIN(date) AS first_date,
                    MAX(date) AS last_date
                FROM workouts
                WHERE user_id = :user_id
                  AND (:start_date IS NULL OR date >= :start_date)
                  AND (:end_date IS NULL OR date <= :end_date)
            """),
            {
                "user_id": user_id,
                "start_date": start_date,
                "end_date": end_date,
            }
        )

        row = result.mappings().one()

    return row

def get_volume_by_date(user_id: int | None = None):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    date,
                    COALESCE(SUM(reps * weight_kg), 0) AS total_volume,
                    COUNT(*) AS sets_count
                FROM workouts
                WHERE (:user_id IS NULL OR user_id = :user_id)
                GROUP BY date
                ORDER BY date DESC
                LIMIT 10
            """),
            {"user_id": user_id}
        )

        rows = result.mappings().all()

    return rows

#Connect with analytics
def get_latest_training_date(user_id: int | None = None):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT MAX(date) AS latest_date
                FROM workouts
                WHERE (:user_id IS NULL OR user_id = :user_id)
            """),
            {"user_id": user_id}
        )

        latest_date = result.scalar()

    return latest_date


def get_workouts_by_date(training_date, user_id: int | None = None):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    id,
                    user_id,
                    date,
                    exercise,
                    category,
                    reps,
                    weight_kg,
                    rest_sec_after,
                    duration_sec,
                    rpe,
                    notes
                FROM workouts
                WHERE date = :training_date
                  AND (:user_id IS NULL OR user_id = :user_id)
                ORDER BY id
            """),
            {
                "training_date": training_date,
                "user_id": user_id,
            }
        )

        rows = result.mappings().all()

    return rows

#get all workouts for analytics
def get_all_workouts(user_id: int | None = None):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    id,
                    user_id,
                    date,
                    exercise,
                    category,
                    reps,
                    weight_kg,
                    rest_sec_after,
                    duration_sec,
                    rpe,
                    notes
                FROM workouts
                WHERE (:user_id IS NULL OR user_id = :user_id)
                ORDER BY date, id
            """),
            {"user_id": user_id}
        )

        rows = result.mappings().all()

    return rows


def get_existing_exercise_names(user_id: int | None = None):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT DISTINCT exercise
                FROM workouts
                WHERE exercise IS NOT NULL
                  AND (:user_id IS NULL OR user_id = :user_id)
                ORDER BY exercise
            """),
            {"user_id": user_id}
        )

        rows = result.scalars().all()

    return list(rows)


def create_exercise_reference_values_table():
    engine = get_engine()

    with engine.connect() as conn:
        conn.execute(
            text("""
                CREATE TABLE IF NOT EXISTS exercise_reference_values (
                    user_id integer NOT NULL,
                    exercise text NOT NULL,
                    exercise_type text NOT NULL,
                    reference_value numeric(8,2) NOT NULL,
                    reference_source text NOT NULL,
                    best_e1rm numeric(8,2),
                    best_working_weight numeric(8,2),
                    best_volume_day numeric(10,2),
                    best_reps_per_set numeric(8,2),
                    best_duration_sec integer,
                    sample_sessions integer NOT NULL DEFAULT 0,
                    updated_at timestamp NOT NULL DEFAULT now(),
                    PRIMARY KEY (user_id, exercise)
                )
            """)
        )
        conn.commit()


def clear_exercise_reference_values(user_id: int | None = None):
    engine = get_engine()

    with engine.connect() as conn:
        if user_id is None:
            conn.execute(text("DELETE FROM exercise_reference_values"))
        else:
            conn.execute(
                text("""
                    DELETE FROM exercise_reference_values
                    WHERE user_id = :user_id
                """),
                {"user_id": user_id}
            )

        conn.commit()


def insert_exercise_reference_values(rows: list[dict]):
    if not rows:
        return

    engine = get_engine()

    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO exercise_reference_values
                (
                    user_id,
                    exercise,
                    exercise_type,
                    reference_value,
                    reference_source,
                    best_e1rm,
                    best_working_weight,
                    best_volume_day,
                    best_reps_per_set,
                    best_duration_sec,
                    sample_sessions,
                    updated_at
                )
                VALUES
                (
                    :user_id,
                    :exercise,
                    :exercise_type,
                    :reference_value,
                    :reference_source,
                    :best_e1rm,
                    :best_working_weight,
                    :best_volume_day,
                    :best_reps_per_set,
                    :best_duration_sec,
                    :sample_sessions,
                    now()
                )
                ON CONFLICT (user_id, exercise)
                DO UPDATE SET
                    exercise_type = EXCLUDED.exercise_type,
                    reference_value = EXCLUDED.reference_value,
                    reference_source = EXCLUDED.reference_source,
                    best_e1rm = EXCLUDED.best_e1rm,
                    best_working_weight = EXCLUDED.best_working_weight,
                    best_volume_day = EXCLUDED.best_volume_day,
                    best_reps_per_set = EXCLUDED.best_reps_per_set,
                    best_duration_sec = EXCLUDED.best_duration_sec,
                    sample_sessions = EXCLUDED.sample_sessions,
                    updated_at = now()
            """),
            rows
        )
        conn.commit()


def get_exercise_reference_values(user_id: int = 1) -> dict:
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    user_id,
                    exercise,
                    exercise_type,
                    reference_value,
                    reference_source,
                    best_e1rm,
                    best_working_weight,
                    best_volume_day,
                    best_reps_per_set,
                    best_duration_sec,
                    sample_sessions,
                    updated_at
                FROM exercise_reference_values
                WHERE user_id = :user_id
                ORDER BY exercise
            """),
            {"user_id": user_id}
        )

        rows = result.mappings().all()

    return {row["exercise"]: dict(row) for row in rows}


def get_workout_exercise_keys(user_id: int = 1) -> list[str]:
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT DISTINCT exercise
                FROM workouts
                WHERE user_id = :user_id
                  AND exercise IS NOT NULL
                ORDER BY exercise
            """),
            {"user_id": user_id}
        )

        rows = result.scalars().all()

    return list(rows)


def get_workout_user_ids() -> list[int]:
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT DISTINCT user_id
                FROM workouts
                WHERE user_id IS NOT NULL
                ORDER BY user_id
            """)
        )

        rows = result.scalars().all()

    return list(rows)



def clear_daily_stats():
    engine = get_engine()

    with engine.connect() as conn:
        conn.execute(text("DELETE FROM daily_exercise_stats"))
        conn.execute(text("DELETE FROM daily_muscle_stats"))
        conn.commit()


def insert_daily_exercise_stats(rows: list[dict]):
    if not rows:
        return

    engine = get_engine()

    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO daily_exercise_stats
                (
                    user_id,
                    date,
                    exercise,
                    exercise_type,
                    sets,
                    working_sets,
                    heavy_sets,
                    target_sets,
                    total_reps,
                    total_duration_sec,
                    total_volume,
                    max_weight,
                    working_weight,
                    best_estimated_1rm,
                    avg_intensity,
                    score_units,
                    target_units,
                    rating_10,
                    algorithmic_effort,
                    updated_at
                )
                VALUES
                (
                    :user_id,
                    :date,
                    :exercise,
                    :exercise_type,
                    :sets,
                    :working_sets,
                    :heavy_sets,
                    :target_sets,
                    :total_reps,
                    :total_duration_sec,
                    :total_volume,
                    :max_weight,
                    :working_weight,
                    :best_estimated_1rm,
                    :avg_intensity,
                    :score_units,
                    :target_units,
                    :rating_10,
                    :algorithmic_effort,
                    now()
                )
                ON CONFLICT (user_id, date, exercise)
                DO UPDATE SET
                    exercise_type = EXCLUDED.exercise_type,
                    sets = EXCLUDED.sets,
                    working_sets = EXCLUDED.working_sets,
                    heavy_sets = EXCLUDED.heavy_sets,
                    target_sets = EXCLUDED.target_sets,
                    total_reps = EXCLUDED.total_reps,
                    total_duration_sec = EXCLUDED.total_duration_sec,
                    total_volume = EXCLUDED.total_volume,
                    max_weight = EXCLUDED.max_weight,
                    working_weight = EXCLUDED.working_weight,
                    best_estimated_1rm = EXCLUDED.best_estimated_1rm,
                    avg_intensity = EXCLUDED.avg_intensity,
                    score_units = EXCLUDED.score_units,
                    target_units = EXCLUDED.target_units,
                    rating_10 = EXCLUDED.rating_10,
                    algorithmic_effort = EXCLUDED.algorithmic_effort,
                    updated_at = now()
            """),
            rows
        )
        conn.commit()


def insert_daily_muscle_stats(rows: list[dict]):
    if not rows:
        return

    engine = get_engine()

    with engine.connect() as conn:
        conn.execute(
            text("""
                INSERT INTO daily_muscle_stats
                (
                    user_id,
                    date,
                    muscle,
                    score_units,
                    target_units,
                    rating_10,
                    updated_at
                )
                VALUES
                (
                    :user_id,
                    :date,
                    :muscle,
                    :score_units,
                    :target_units,
                    :rating_10,
                    now()
                )
                ON CONFLICT (user_id, date, muscle)
                DO UPDATE SET
                    score_units = EXCLUDED.score_units,
                    target_units = EXCLUDED.target_units,
                    rating_10 = EXCLUDED.rating_10,
                    updated_at = now()
            """),
            rows
        )
        conn.commit()


def get_daily_exercise_stats(exercise: str):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    user_id,
                    date,
                    exercise,
                    exercise_type,
                    sets,
                    working_sets,
                    heavy_sets,
                    target_sets,
                    total_reps,
                    total_duration_sec,
                    total_volume,
                    max_weight,
                    working_weight,
                    best_estimated_1rm,
                    avg_intensity,
                    score_units,
                    target_units,
                    rating_10,
                    algorithmic_effort,
                    updated_at
                FROM daily_exercise_stats
                WHERE lower(exercise) = lower(:exercise)
                ORDER BY date
            """),
            {"exercise": exercise}
        )

        rows = result.mappings().all()

    return rows


def get_daily_muscle_stats(muscle: str):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    user_id,
                    date,
                    muscle,
                    score_units,
                    target_units,
                    rating_10,
                    updated_at
                FROM daily_muscle_stats
                WHERE lower(muscle) = lower(:muscle)
                ORDER BY date
            """),
            {"muscle": muscle}
        )

        rows = result.mappings().all()

    return rows

def get_exercise_aggregate_history(exercise: str):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    user_id,
                    date,
                    exercise,
                    exercise_type,
                    sets,
                    working_sets,
                    heavy_sets,
                    target_sets,
                    total_reps,
                    total_duration_sec,
                    total_volume,
                    max_weight,
                    working_weight,
                    best_estimated_1rm,
                    avg_intensity,
                    score_units,
                    target_units,
                    rating_10,
                    algorithmic_effort,
                    updated_at
                FROM daily_exercise_stats
                WHERE exercise = :exercise
                ORDER BY date
            """),
            {"exercise": exercise}
        )

        rows = result.mappings().all()

    return rows


def get_exercise_stats_for_period(
    user_id: int = 1,
    start_date=None,
    end_date=None,
    exercise: str | None = None,
):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    user_id,
                    date,
                    exercise,
                    exercise_type,
                    sets,
                    working_sets,
                    heavy_sets,
                    target_sets,
                    total_reps,
                    total_duration_sec,
                    total_volume,
                    max_weight,
                    working_weight,
                    best_estimated_1rm,
                    avg_intensity,
                    score_units,
                    target_units,
                    rating_10,
                    algorithmic_effort,
                    updated_at
                FROM daily_exercise_stats
                WHERE user_id = :user_id
                  AND (:start_date IS NULL OR date >= :start_date)
                  AND (:end_date IS NULL OR date <= :end_date)
                  AND (:exercise IS NULL OR exercise = :exercise)
                ORDER BY date, exercise
            """),
            {
                "user_id": user_id,
                "start_date": start_date,
                "end_date": end_date,
                "exercise": exercise,
            }
        )

        rows = result.mappings().all()

    return rows


def get_muscle_aggregate_history(muscle: str):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    user_id,
                    date,
                    muscle,
                    score_units,
                    target_units,
                    rating_10,
                    updated_at
                FROM daily_muscle_stats
                WHERE muscle = :muscle
                ORDER BY date
            """),
            {"muscle": muscle}
        )

        rows = result.mappings().all()

    return rows


def get_muscle_stats_for_period(
    user_id: int = 1,
    start_date=None,
    end_date=None,
    muscle: str | None = None,
):
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT
                    user_id,
                    date,
                    muscle,
                    score_units,
                    target_units,
                    rating_10,
                    updated_at
                FROM daily_muscle_stats
                WHERE user_id = :user_id
                  AND (:start_date IS NULL OR date >= :start_date)
                  AND (:end_date IS NULL OR date <= :end_date)
                  AND (:muscle IS NULL OR muscle = :muscle)
                ORDER BY date, muscle
            """),
            {
                "user_id": user_id,
                "start_date": start_date,
                "end_date": end_date,
                "muscle": muscle,
            }
        )

        rows = result.mappings().all()

    return rows


def get_available_exercise_keys():
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT DISTINCT exercise
                FROM daily_exercise_stats
                ORDER BY exercise
            """)
        )

        rows = result.scalars().all()

    return list(rows)


def get_available_muscle_keys():
    engine = get_engine()

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT DISTINCT muscle
                FROM daily_muscle_stats
                ORDER BY muscle
            """)
        )

        rows = result.scalars().all()

    return list(rows)


def clear_daily_stats_for_date(training_date, user_id: int | None = None):
    engine = get_engine()

    with engine.connect() as conn:
        conn.execute(
            text("""
                DELETE FROM daily_exercise_stats
                WHERE date = :training_date
                  AND (:user_id IS NULL OR user_id = :user_id)
            """),
            {
                "training_date": training_date,
                "user_id": user_id,
            }
        )

        conn.execute(
            text("""
                DELETE FROM daily_muscle_stats
                WHERE date = :training_date
                  AND (:user_id IS NULL OR user_id = :user_id)
            """),
            {
                "training_date": training_date,
                "user_id": user_id,
            }
        )

        conn.commit()
